{
 "title": "Test Sempre Vicini",
 "description": "Prova con Broccio per visualizzazione lato portale Sempre Vicini",
 "time": { "from": "now/M", "to": "now/M" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "processInstanceId",
    "label": "processInstanceId",
    "query": "SHOW TAG VALUES WITH KEY=processInstanceId"
   }
  ]
 },
 "panels": [
  {
   "title": "Battiti",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Battiti cardiaci",
     "measurement": "pulse",
     "select": [
      [
       { "params": [ "pulse" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "processInstanceId", "operator": "=~", "value": "/^$processInstanceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Battiti",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Battiti (bpm)",
     "measurement": "pulse",
     "select": [
      [
       { "params": [ "pulse" ], "type": "field" },
       { "params": [ "Frequency" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "processInstanceId", "operator": "=~", "value": "/^$processInstanceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Ossigenazione del sangue",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Ossigenazione del sangue",
     "measurement": "spo2",
     "select": [
      [
       { "params": [ "spo2" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "processInstanceId", "operator": "=~", "value": "/^$processInstanceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Ossigenazione del sangue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Ossigenazione (%)",
     "measurement": "spo2",
     "select": [
      [
       { "params": [ "spo2" ], "type": "field" },
       { "params": [ "Frequency" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "processInstanceId", "operator": "=~", "value": "/^$processInstanceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperatura corporea",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Temperatura corporea",
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "processInstanceId", "operator": "=~", "value": "/^$processInstanceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperatura corporea",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Temperatura (°C)",
     "measurement": "temperature",
     "query": "SELECT \"temperature\" FROM \"thermometer\" WHERE (\"processInstanceId\" =~ /^$processInstanceId$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "processInstanceId", "operator": "=~", "value": "/^$processInstanceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Glucosio",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Glucosio",
     "measurement": "glucose",
     "select": [
      [
       { "params": [ "glucose" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "processInstanceId", "operator": "=~", "value": "/^$processInstanceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Glucosio",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Glucosio (mg/dl)",
     "measurement": "glucose",
     "select": [
      [
       { "params": [ "glucose" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "processInstanceId", "operator": "=~", "value": "/^$processInstanceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Diastolica",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Pressione minima",
     "measurement": "diastolic",
     "select": [
      [
       { "params": [ "diastolic" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "processInstanceId", "operator": "=~", "value": "/^$processInstanceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Sistolica",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Pressione Massima",
     "measurement": "systolic",
     "select": [
      [
       { "params": [ "systolic" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "processInstanceId", "operator": "=~", "value": "/^$processInstanceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressione sanguigna",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Sistolica (mmHg)",
     "measurement": "systolic",
     "select": [
      [
       { "params": [ "systolic" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "processInstanceId", "operator": "=~", "value": "/^$processInstanceId$/" }
     ]
    },
    {
     "alias": "Diastolica (mmHg)",
     "measurement": "diastolic",
     "select": [
      [
       { "params": [ "diastolic" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "processInstanceId", "operator": "=~", "value": "/^$processInstanceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Peso Corporeo",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Peso Corporeo",
     "measurement": "weight",
     "select": [
      [
       { "params": [ "weight" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "processInstanceId", "operator": "=~", "value": "/^$processInstanceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Peso Corporeo",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Peso (Kg)",
     "measurement": "weight",
     "select": [
      [
       { "params": [ "weight" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "processInstanceId", "operator": "=~", "value": "/^$processInstanceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Camera",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "alias": "Movimento",
     "measurement": "movement",
     "select": [
      [
       { "params": [ "motion" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "processInstanceId", "operator": "=~", "value": "/^$processInstanceId$/" }
     ]
    }
   ]
  }
 ]
}